# Generated by Django 5.2 on 2025-05-06 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customererror',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='customererror',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='customererror',
            name='is_fixed',
        ),
        migrations.AddField(
            model_name='cleanentry',
            name='customer_name',
            field=models.CharField(default='', max_length=255),  # Changed from timezone.now
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleanentry',
            name='identifier',
            field=models.CharField(default='', max_length=100),  # Changed from timezone.now
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customererror',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.batchhistory'),  # Changed from timezone.now
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customererror',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customererror',
            name='customer_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores additional customer details in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='customererror',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customererror',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customererror',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customererror',
            name='severity',
            field=models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=20),
        ),
        migrations.AddField(
            model_name='customererror',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ok', 'OK')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customererror',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customererror',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_errors', to=settings.AUTH_USER_MODEL),  # Changed from timezone.now
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customererror',
            name='xml_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='batchhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batchhistory',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleanentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='account_number',
            field=models.CharField(default='', max_length=100),  # Changed from timezone.now
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customererror',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='customer_name',
            field=models.CharField(default='', max_length=255),  # Changed from timezone.now
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customererror',
            name='error_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=100),  # Changed from timezone.now
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RecentUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('customer_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_ids', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedCustomerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('trade_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('customer_code', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('total_loan_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]