# Generated by Django 5.2 on 2025-05-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customererror_options_and_more'),
    ]

    operations = [
    ]
