# Generated by Django 5.2 on 2025-04-23 05:29
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_alter_customererror_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='customererror',
            options={},
        ),
        migrations.AddField(
            model_name='customererror',
            name='customer_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customererror',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='error_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='line_number',
            field=models.CharField(blank=True, max_length=50),  # Removed django.utils.timezone.now default
        ),
        migrations.AlterField(
            model_name='customererror',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='national_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_errors', to=settings.AUTH_USER_MODEL),  # Changed default=django.utils.timezone.now to null=True
        ),
    ]