# Generated by Django 5.2 on 2025-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_default_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedcustomerdata',
            name='birth_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
