# Generated by Django 5.2 on 2025-04-23 05:32

from django.db import migrations
from django.db import models



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customererror_options_and_more'),
    ]

   
    operations = [
        migrations.AddField(
            model_name='customererror',
            name='customer_details_json',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]