# Generated by Django 5.2 on 2025-05-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_submittedcustomerdata_birth_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customererror',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customererror',
            name='message',
            field=models.TextField(),
        ),
    ]
