# Generated by Django 5.2 on 2025-04-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customererror_customer_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customererror',
            name='customer_details_json',
        ),
    ]
