# Generated by Django 5.2 on 2025-05-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customererror_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchhistory',
            name='clean_xml_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
