# Generated by Django 5.2 on 2025-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_customererror_customer_details_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customererror',
            name='customer_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores additional customer details in JSON format', null=True),
        ),
    ]
