# Generated by Django 5.2 on 2025-04-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customererror_customer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customererror',
            name='customer_details_json',
            field=models.JSONField(blank=True, help_text='(Optional) Duplicate or processed customer details', null=True),
        ),
    ]
