# Generated by Django 5.2 on 2025-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customererror_customer_details_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customererror',
            name='customer_details_json',
            field=models.JSONField(blank=True, help_text='Alternative structure for additional parsed customer info', null=True),
        ),
    ]
