# Generated by Django 5.2 on 2025-04-24 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customererror_customer_details_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedCustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('trade_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('customer_code', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('total_loan_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
